export const DASHBOARD_LINKS = {
  eventsSevere: '/events?severity=严重',
  events24h: '/events?time_range=24h',
  eventsMaintenance: '/events?maintenance_only=1',
  nodes: '/nodes',
  nodesAbnormal: '/nodes?abnormal=1',
  nodesPendingOnboarding: '/nodes?onboarding=pending',
  nodesPaused: '/nodes?run_status=暂停',
  nodesRetired: '/nodes?lifecycle=已退役',
  targets: '/targets',
  targetsAbnormal: '/targets?abnormal=1',
  targetsPaused: '/targets?run_status=暂停',
  targetsArchived: '/targets?run_status=已归档',
  settings: '/settings',
  assetDecisions: '/asset-decisions',
  vps: '/vps',
  vpsUnreviewed: '/vps?renewal_decision=unreviewed',
  vpsToCancel: '/vps?lifecycle_status=to_cancel',
  vpsToMigrate: '/vps?lifecycle_status=to_migrate',
  subscriptionsRenew30d: '/subscriptions?renew_within_days=30',
} as const
