export const DASHBOARD_LINKS = {
  eventsSevere: '/events?severity=严重',
  events24h: '/events?time_range=24h',
  eventsMaintenance: '/events?maintenance_only=1',
  monitoring: '/monitoring',
  monitoringAbnormal: '/monitoring?abnormal=1',
  monitoringPendingOnboarding: '/monitoring?onboarding=pending',
  monitoringPaused: '/monitoring?run_status=暂停',
  monitoringRetired: '/monitoring?lifecycle=已退役',
  targets: '/targets',
  targetsAbnormal: '/targets?abnormal=1',
  targetsPaused: '/targets?run_status=暂停',
  targetsArchived: '/targets?run_status=已归档',
  settings: '/settings',
  assetDecisionsNeedsDecision: '/asset-decisions?view=needs_decision&renew_within_days=30',
  assetDecisionsMigrationRetirement: '/asset-decisions?view=needs_decision&renew_within_days=30&scenario=migration_retirement',
  assetDecisionsRenewal: '/asset-decisions?view=renewal&renew_within_days=30',
  assetDecisionsProvider: '/asset-decisions?view=provider&renew_within_days=30',
  assetDecisionsCost: '/asset-decisions?view=cost&renew_within_days=30&scenario=budget_reduction',
  assetDecisionsEvidence: '/asset-decisions?view=evidence&renew_within_days=30&scenario=evidence_cleanup',
  vps: '/vps',
  vpsCancellationAttention: '/vps?view=cancellation_attention',
  vpsUnreviewed: '/vps?renewal_decision=unreviewed',
  vpsToCancel: '/vps?lifecycle_status=to_cancel',
  vpsToMigrate: '/vps?lifecycle_status=to_migrate',
  subscriptionsRenew30d: '/subscriptions?renew_within_days=30',
} as const
