#!/usr/bin/env bash
# Per-boot reconciliation for the Houfeng dev environment.
# Starts PostgreSQL, ensures the houfeng role/database exist, and materializes a
# local (non-committed) center env file. Idempotent: safe to run on every boot.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# 1. Start the PostgreSQL cluster if it is not already accepting connections.
PG_VER="$(ls /etc/postgresql 2>/dev/null | sort -V | tail -1 || true)"
if [ -z "$PG_VER" ]; then
  echo "[start] ERROR: no PostgreSQL cluster found; run .cursor/install.sh first" >&2
  exit 1
fi

if ! pg_isready -q -h localhost -p 5432; then
  echo "[start] starting PostgreSQL cluster $PG_VER/main"
  sudo pg_ctlcluster "$PG_VER" main start || true
fi

# Wait for readiness (up to ~30s).
for _ in $(seq 1 30); do
  if pg_isready -q -h localhost -p 5432; then break; fi
  sleep 1
done
pg_isready -h localhost -p 5432

# 2. Ensure the application role and database exist (idempotent).
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='houfeng'" | grep -q 1; then
  echo "[start] creating role houfeng"
  sudo -u postgres psql -c "CREATE ROLE houfeng LOGIN PASSWORD 'houfeng';"
fi
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='houfeng'" | grep -q 1; then
  echo "[start] creating database houfeng"
  sudo -u postgres createdb -O houfeng houfeng
fi

# 3. Materialize a local center env file (kept out of git; not a production secret).
#    The center applies embedded migrations and seeds the initial admin on first run.
ENV_DIR="$HOME/.config/houfeng"
ENV_FILE="$ENV_DIR/center.env"
mkdir -p "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  echo "[start] writing local center env: $ENV_FILE"
  HMAC="$(head -c 48 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Local development center configuration (generated by .cursor/start.sh).
# Dev-only values for an ephemeral local PostgreSQL; do not use in production.
export HOUFENG_HTTP_ADDR=:8080
export HOUFENG_WEB_DIST_DIR=$REPO_ROOT/web/dist
export HOUFENG_DATABASE_URL='postgres://houfeng:houfeng@localhost:5432/houfeng?sslmode=disable'
export HOUFENG_DATABASE_REQUIRE_TLS=false
export HOUFENG_PUBLIC_BASE_URL='http://localhost:8080'
export HOUFENG_INCIDENT_SWEEP_INTERVAL=5s
export HOUFENG_INITIAL_USERNAME=admin
export HOUFENG_INITIAL_PASSWORD='HoufengDev123!'
export HOUFENG_SESSION_HMAC_KEY='$HMAC'
EOF
fi

echo "[start] ready: PostgreSQL up, database 'houfeng' present, env at $ENV_FILE"
